---
- hosts: workstation

  tasks:
    - name: Installs extra packages
      apt: name={{item}} state=present
      with_items:
        - build-essential
        - ubuntu-restricted-extras
        - ttf-mscorefonts-installer
        - wine
        - playonlinux
