---
cache_dir: ~/Library/Caches/battleschool

sources:
  local:
    - homebrew.yml
    - git.yml
    - bash.yml
    - golang.yml
    - hyper-key.yml
    - lastpass.yml
    - docker-toolbox.yml
    - sonos.yml
    - slate.yml
    - vpn.yml
    - intellij-idea-ce.yml
    - transmission.yml

  git:
   - name: 'osx'
     repo: 'https://github.com/spencergibb/ansible-osx'
     playbooks:
        - atom.yml
        - chrome-stable.yml
        - dropbox.yml
        - iterm2.yml
        - java8.yml
        - spectacle.yml
        - skype.yml
