---
cache_dir: ~/.battleschool

sources:
  local:
    - base-ubuntu.yml
    - bash.yml
    - atom.yml
    - slack.yml
    - git.yml
    - golang.yml
    #- hyper-key.yml
    - fonts.yml
    - docker.yml
#    - lastpass.yml
#    - docker-toolbox.yml
#    - sonos.yml
#    - slate.yml
#    - vpn.yml
    - intellij-idea-ce.yml
#    - transmission.yml
